services:
  backend:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      ORIGIN: ${ORIGIN}
      SECRET: ${SECRET}
      SECRETEXPIRED: ${SECRETEXPIRED}
      USER: ${USER}
    restart: always
    ports:
      - '${PORT}:5555'
    command: >
      sh -c "npm run seed:dist && npm run start:prod"
