services:
  backend:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    env_file: .env
    restart: always
    ports:
      - '5555:5555'
    command: >
      sh -c "npm run seed && npm run start:prod"
