name: WhatBorder Backend

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Debug SSH key
        run: |
          ls -lah ~/.ssh || true
          echo "SSH_HOST=${{ secrets.SSH_HOST }}"
          head -n 5 ~/.ssh/id_ed25519 || true
          tail -n 5 ~/.ssh/id_ed25519 || true

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ secrets.SSH_HOST }} << 'EOF'
          if [ ! -d ~/WhatBorder ]; then
            git clone https://github.com/Z4nR/WhatBorder
          fi
          cd ~/WhatBorder
          git pull origin main
          cd server
          docker compose down --remove-orphans
          docker compose --project-name placeborder up --build -d
          docker image prune -a -f
          EOF
